name: web_scraping
channels:
  - defaults
  - conda-forge
dependencies:
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bottleneck=1.3.5
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2023.5.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - cryptography=39.0.1
  - idna=3.4
  - intel-openmp
  - libcxx
  - libffi=3.4.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
#  - ncurses
  - numexpr=2.8.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openssl=1.1.1t
  - pandas=1.5.3
  - pip=23.0.1
  - pycparser=2.21
  - pyopenssl=23.0.0
  - pysocks=1.7.1
  - python=3.11.3
  - python-dateutil=2.8.2
  - pytz=2022.7
#  - readline
  - requests=2.29.0
  - setuptools=66.0.0
  - six=1.16.0
  - soupsieve=2.4
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tk=8.6.12
  - tzdata=2023c
  - urllib3=1.26.15
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13